version: "3.9"

services:
  service1:
    image: alpine
    container_name: service_one
    command: ["sh", "-c", "while true; do echo Service 1 running; sleep 5; done"]

  service2:
    image: alpine
    container_name: service_two
    command: ["sh", "-c", "while true; do echo Service 2 running; sleep 5; done"]
