services:
  nginx:
    build: ./requirements/nginx
    image: inception-nginx
    container_name: nginx
    pull_policy: never
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
      - ./requirements/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    image: inception-wordpress
    container_name: wp-php
    pull_policy: never
    restart: unless-stopped
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    image: inception-mariadb
    container_name: mariadb
    pull_policy: never
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
