services:
  nginx:
    build: ./requirements/nginx
    image: inception-nginx
    container_name: nginx
    pull_policy: never
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
      - ./requirements/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - wordpress
  wordpress:
    build: ./requirements/wordpress
    image: inception-wordpress
    container_name: wp-php
    pull_policy: never
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html
    secrets:
      - db_name
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
    depends_on:
      - mariadb
  mariadb:
    build: ./requirements/mariadb
    image: inception-mariadb
    container_name: mariadb
    pull_policy: never
    restart: unless-stopped
    secrets:
      - db_name
      - db_user
      - db_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  wp_data:

secrets:
  db_name:
    file: ../secrets/db_name
  db_user:
    file: ../secrets/db_user
  db_password:
    file: ../secrets/db_password
  wp_admin_user:
    file: ../secrets/wp_admin_user
  wp_admin_password:
    file: ../secrets/wp_admin_password
  wp_admin_email:
    file: ../secrets/wp_admin_email
