services:
  nginx:
    build: ./requirements/nginx
    image: inception-nginx
    container_name: nginx
    pull_policy: never
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
      - ./requirements/nginx/certs:/etc/nginx/certs:ro
      - ./requirements/bonus/static:/var/www/static:ro
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    image: inception-wordpress
    container_name: wp-php
    pull_policy: never
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/html
    secrets:
      - db_name
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_user_name
      - wp_user_password
      - wp_user_email
      - redis_password
    depends_on:
      - mariadb
      - redis

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    pull_policy: never
    restart: unless-stopped
    secrets:
      - db_name
      - db_user
      - db_password
    volumes:
      - db_data:/var/lib/mysql

  redis:
    build: ./requirements/redis
    image: redis
    container_name: redis
    pull_policy: never
    restart: unless-stopped
    secrets:
      - redis_password

  ftp:
    build: ./requirements/bonus/ftp
    image: inception-ftp
    container_name: ftp
    pull_policy: never
    restart: unless-stopped
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wp_data:/var/www/html
      - ./requirements/bonus/ftp/certs:/etc/vsftpd/certs:ro

    secrets:
      - ftp_user
      - ftp_password
    depends_on:
      - wordpress

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lseeger/data/wordpress
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/lseeger/data/mariadb

secrets:
  db_name:
    file: ../secrets/db_name
  db_user:
    file: ../secrets/db_user
  db_password:
    file: ../secrets/db_password
  wp_admin_user:
    file: ../secrets/wp_admin_user
  wp_admin_password:
    file: ../secrets/wp_admin_password
  wp_admin_email:
    file: ../secrets/wp_admin_email
  wp_user_name:
    file: ../secrets/wp_user_name
  wp_user_password:
    file: ../secrets/wp_user_password
  wp_user_email:
    file: ../secrets/wp_user_email
  redis_password:
    file: ../secrets/redis_password
  ftp_user:
    file: ../secrets/ftp_user
  ftp_password:
    file: ../secrets/ftp_password
